# Generated by Django 5.0.2 on 2024-07-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
