# Generated by Django 5.2 on 2025-05-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_about_blogimage_blogpost_certification_projectimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='value',
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(default=0, upload_to='skill/'),
            preserve_default=False,
        ),
    ]
